### ISSUE TITLE
Variables are NULL

### ISSUE THREAD

**Issue by sweebee** [tester22/pimatic-plex#1]
The plugin doesn't work perfectly anymore. paused and stop and some other variables don't work.

**Comment by tester22** [comment]
I am not using this any more but you are welcome to provide any patches.

**Comment by sweebee** [comment]
Found out it works fine, but when its not playing (stopped) the variables are NULL. I think leaving it empty like ```""``` is better? and de default state is stopped, else it is playing or paused?

How do you think about that? I think its more  clear?

**Comment by sweebee** [comment]
```
    _getStatus: () ->
      @_plexClient.query("/status/sessions").then( (result) =>
        @_state = "stopped"
        @_currentTitle = ""
        @_currentType = ""
        @_currentProgress = 0
        @_currentShow = ""
        @_currentProduct = ""
        @_currentClient = ""
...
```

**Comment by sweetpi** [comment]
@sweebee Could you check, when the case `plexClientFound == false` (https://github.com/tester22/pimatic-plex/blob/master/plex.coffee#L150) does happen?

Is this only the case if it is not connected or when the player was stopped?

**Comment by sweebee** [comment]
The plex api only shows data if a plex client is playing or paused. If a client is stopped it doesn't show up in the xml feed. the variable ```result``` is not empty but shows: 
```
{ _elementType: 'MediaContainer', _children: [] }
```
